### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by skrimxyz** [theManiKh/qb-whiteboard#1]
After changing the image 3 or 4 time I cann't change the image again

**Comment by theMani-kh** [comment]
> After changing the image 3 or 4 time I cann't change the image again

Target or Input not working or image not changed?

**Comment by skrimxyz** [comment]
> > After changing the image 3 or 4 time I cann't change the image again
> 
> Target or Input not working or image not changed?

target and input works perfectly, just images are not changing

**Comment by skrimxyz** [comment]
@theManiKh did you find a fix?

**Comment by theMani-kh** [comment]
> @theManiKh did you find a fix?

Yes, I checked and it was fix. I tried with 10 diffrent images. I think problem is from your client. Check last version.
